on: [push]
name: Linux_ACR
az acr repository list --name acr188 --output table
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        - name: Azure PowerShell Action
          uses: Azure/powershell@v1
          with:
            # Specify the Az PowerShell script here.
            inlineScript: |
            az acr repository list --name acr188 --output table
