on: [push]
name: Linux_ACR
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        - name: Run Azure PowerShell script
          uses: azure/powershell@v1
          with:
            inlineScript: |
                az acr repository list --name acr188 --output table
            azPSVersion: "latest"
         
